server:
  port: 8080

spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        open-in-view: false
    defer-datasource-initialization: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      client-name: library
      timeout: 10000
  kafka:
    bootstrap-servers: localhost:9092


book:
  key-prefix: book_lock
  reserve-topic: book.reservation

logging:
  config: classpath:logback-local.xml

book-url: http://localhost:8080/books

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:library-test
    driver-class-name: org.h2.Driver
    username: sa
    password:

