server:
  port: 8080

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:library-test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        open-in-view: false
    defer-datasource-initialization: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      client-name: library
      timeout: 10000

book:
  key-prefix: book_lock


logging:
  config: classpath:logback-local.xml
