### 책 등록
POST {{host}}/books
Content-Type: application/json

{
  "title": "test 책",
  "author": "test",
  "publisher": "에이콘",
  "isbn": "1234567895",
  "quantity": 10,
  "price": 30000
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.global.set("bookId", response.body.id)
%}

### 책 id 로 조회
GET {{host}}/books/{{bookId}}
Content-Type: application/json


### 책 추가 주문(예약)
PATCH {{host}}/books/order
Content-Type: application/json

{
  "id": {{bookId}},
  "quantity": 1,
  "orderType": "RESERVATION",
  "orderAt": "2024-01-30T05:30:00+09:00"
}

### 책 추가 주문
PATCH {{host}}/books/order
Content-Type: application/json

{
  "id": {{bookId}},
  "quantity": 1,
  "orderType": "NOW"
}

### 책 폐기
PATCH {{host}}/books/discard
Content-Type: application/json

{
  "id": {{bookId}},
  "quantity": 5
}

### 책 예약 주문 실행 api
POST {{host}}/books/order/reserve
Content-Type: application/json

