### 책 등록
POST http://localhost:8080/library/api/v1/book
Content-Type: application/json

{
  "title": "토비의 스프링",
  "author": "이일민",
  "publisher": "에이콘",
  "isbn": "1234567890",
  "description": "토비의 스프링 3.1",
  "quantity": 1,
  "price": 30000
}

### 책 id 로 조회
GET http://localhost:8080/library/api/v1/book/1
Content-Type: application/json


### 책 추가 주문
PATCH http://localhost:8080/library/api/v1/book/order
Content-Type: application/json

{
  "id": 1,
  "quantity": 1
}

### 책 폐기
PATCH http://localhost:8080/library/api/v1/book/discard
Content-Type: application/json

{
  "id": 1,
  "quantity": 5
}

