### 책 등록
POST {{host}}/library/api/book
Content-Type: application/json

{
  "title": "토비의 스프링2",
  "author": "이일민",
  "publisher": "에이콘",
  "isbn": "1234567893",
  "quantity": 10,
  "price": 30000
}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.global.set("bookId", response.body.id)
%}

### 책 id 로 조회
GET {{host}}/library/api/book/{{bookId}}
Content-Type: application/json


### 책 추가 주문
PATCH {{host}}/library/api/book/order
Content-Type: application/json

{
  "id": {{bookId}},
  "quantity": 1
}

### 책 폐기
PATCH {{host}}/library/api/book/discard
Content-Type: application/json

{
  "id": {{bookId}},
  "quantity": 5
}

