### 책 대여 API
POST {{host}}/library/api/book/borrow
Content-Type: application/json

{
  "customerId": {{customerId}},
  "borrowBooks": [
    {
      "bookId": 2,
      "quantity": 1
    },
    {
      "bookId": 3,
      "quantity": 1
    }
  ]
}



### 책 반납 API
POST {{host}}/library/api/book/return
Content-Type: application/json

{
    "id": 1,
    "customerId": {{customerId}},
    "returnBooks": [
      {
        "bookId": 2,
        "quantity": 1
      },
      {
        "bookId": 3,
        "quantity": 1
      }
    ]
}

